name: release version

on:
  push:
    branches:
      - main

jobs:
  release-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Version
        run: |
          TS=$(date +%s)
          echo "VERSION_TS=$TS" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            quay.io/garth/datadog-keycloak:latest
            quay.io/garth/datadog-keycloak:${{ env.VERSION_TS }}
      - name: Tag
        uses: cardinalby/git-tag-action@master
        env:
          TAG: v${{ env.VERSION_TAG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
